### ISSUE TITLE
vim-php.com site down?

### ISSUE THREAD

**Issue by mlopezgva** [vim-php/phpctags#83] opened 2019-05-10 21:54 UTC
I was trying to get the phar using `http://vim-php.com/phpctags/install/phpctags.phar` but it can't resolve the hostname... Any alternatives? Thank you.

**Comment by jmramos02** [comment] 2019-06-06 10:33
experiencing this. looks like it

**Comment by jmramos02** [comment] 2019-06-06 10:39
Looks like we need to build from source

**Comment by Mte90** [comment] 2019-10-11 07:52
Confirmed the issue and also the new release is not available, but can be loaded in the release of github.

**Comment by mlopezgva** [comment] 2019-10-11 08:26
I downloaded the source 0.7.0, but when I `make` it, it shows version 0.6.1?

**Comment by Mte90** [comment] 2019-10-11 08:27
maybe they released a new version but didn't bump the version

**Comment by mlopezgva** [comment] 2019-10-11 08:30
Well, I just updated it (apparently to 0.6.1...), I hope it still works as expected. :-)

**Comment by InFog** [comment] 2020-07-02 06:37
http://vim-php.com/phpctags/install/phpctags.phar is fixed now and on 0.8.0

**Closed by InFog** 2020-07-02 06:37 UTC

**Comment by mlopezgva** [comment] 2021-04-24 17:32
It seems like it's not working...

![image](https://user-images.githubusercontent.com/996070/115967580-b5fb6a00-a533-11eb-8c16-aa461c113f55.png)

_"vim-php.com" not found_

**Comment by InFog** [comment] 2021-04-26 14:39
It seems to be down. I'm not sure who can help.

We can still update the documentation to point to github instead.
